name: Lighthouse CI

on:
  workflow_dispatch:
  schedule:
    - cron: '30 12 1 1,7 *' # run on the 1st day of January and July, every year.

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        id: lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://jpdiaz.dev/
            https://dev.jpdiaz.dev/
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Add comment with Lighthouse action URL
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PUBLIC_GITHUB_TOKEN }}
          script: |
            const runId = context.runId;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const actionUrl = `https://github.com/${owner}/${repo}/actions/runs/${runId}`;
            const commentBody = `
            **Check the Lighthouse CI Report** 🚀

            1. **Audit URL**:\`jpdiaz.dev/\` & \`dev.jpdiaz.dev/\`
            2. **Open the [Lighthouse CI action here](${actionUrl})**
            3. **Check the Report**:
               - Click on \`lighthouse\` > \`Audit URLs using Lighthouse\` > \`Uploading\` > \`open the report\` to see the full report.
            4. **Unlighthouse Report on Netlify**:
               - [https://performance-jpdiaz.netlify.app/](https://performance-jpdiaz.netlify.app/)
            `;

            github.rest.issues.createComment({
              owner: owner,
              repo: repo,
              issue_number: context.issue.number,
              body: commentBody
            });
