# This workflow will run Unlighthouse CI and deploy the results to Netlify
# https://github.com/JuanPabloDiaz/unlighthouse
# Visit https://status.jpdiaz.dev to see the results (https://performance-jpdiaz.netlify.app/)
name: Unlighthouse Report on Netlify

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  schedule:
    - cron: '30 12 1 1,7 *' # run on the 1st day of January and July, every year.

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: npm install -g @unlighthouse/cli puppeteer netlify-cli

      - name: Unlighthouse assertions and client
        run: unlighthouse-ci --site https://jpdiaz.dev/ --budget 75 --build-static

      - name: Deploy
        run: netlify deploy --dir=.unlighthouse --prod --message="New Release Deploy from GitHub Actions"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
